project:
  type: website
  # Where the built site should be written
  output-dir: docs
  # Make sure our custom assets are copied into the output
  resources:
    - styles.css
    - script.js
    - assets/after.html

website:
  title: "EliOra Tech Solutions"
  # Disable Quarto's default navigation bar so we can use our own
  navbar: false

format:
  html:
    # Use our custom stylesheet for all pages
    css: styles.css
    toc: false
    # Inject the after‑body HTML to load Three.js, Vanta.js, and our script
    include-after-body: assets/after.html
    # Render pages with a custom layout so Quarto doesn't add its own grid or header
    page-layout: custom